include $(ROOT)/share/yahoo_cfg/Make.defs

# to build a package - run 
# first install the _build package from dist
# $ yinst inst miners_hive_build 
# then build in the main directory - $ ant package
# then in the yinst directory
# $ gmake package
# OR
# $ gmake package-release
# to clean up -
# $ gmake package-clean
#
#
# Set this variable to be able to make link packages in the future
IN_PACKAGE=1

include $(ROOT)/share/yahoo_cfg/Make.rules
# Do not place any rules or targets above this line
